# Generated by Django 4.2.4 on 2023-10-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YTDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'URL братель',
                'verbose_name_plural': 'URL братели',
            },
        ),
    ]
