# Generated by Django 4.2.4 on 2023-10-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yt_download', '0003_remove_ytdownload_video_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YTDownload',
        ),
    ]
